# Generated by Django 4.2.6 on 2023-12-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_studentprofile_saved_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='saved_jobs',
            field=models.ManyToManyField(null=True, related_name='saved', to='myapp.jobs'),
        ),
    ]
